services:
  - type: web
    name: voxly-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: APP_ENV
        value: production
      - key: MAX_AUDIO_DURATION_SECONDS
        value: "300"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_VERIFY_SID
        sync: false
      - key: JWT_SECRET
        sync: false
